version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: jauzK8c0AfAMy6
      POSTGRES_USER: postgres
      POSTGRES_DB: bookkeeping_tool
    ports:
      - "5432:5432"
    volumes:
      - db_data:/data/postgresql
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
  springboot-app:
    image: javabeans108/bookkeeping-tool:3.0.1
    container_name: bookkeeping-tool
    ports:
      - "8080:8080"
    environment:
      POSTGRES_PASSWORD: jauzK8c0AfAMy6
      POSTGRES_USER: postgres
      DATABASE_URL: jdbc:postgresql://db:5432/bookkeeping_tool
    depends_on:
      - db
volumes:
    db_data: