name: Build and publish Docker Image CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Set docker image version'
        required: true
        type: string

jobs:
  build_image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Node
        uses: actions/setup-node@4.3.0
        with:
          node-version: 22.x
          
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag javabeans108/bookkeeping-tool:${{ inputs.version }} --tag javabeans108/bookkeeping-tool:latest

      - name: Push Docker Image
        run: docker push javabeans108/bookkeeping-tool:${{ inputs.version }}
